
/**************************************************************
 *	
 *	sword, 8 bit, 11025Hz,
 *	1 channel, 8013 bytes/channel
 *	Total Size: 1 * 8013 + 4 (header) = 8057 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\backv\Desktop\sword.wav
 *	Time-stamp: Mon Apr 03 20:07:20 2017
 *	
 **************************************************************/

#ifndef __SWORDH__
#define __SWORDH__

#define SWORDFREQ 11025
#define SWORDLEN 8013

extern const unsigned char sword[8013];

#endif /* __SWORDH__ */
