
/**************************************************************
 *	
 *	theme, 8 bit, 11025Hz,
 *	1 channel, 972288 bytes/channel
 *	Total Size: 1 * 972288 + 4 (header) = 972332 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\backv\Desktop\theme.wav
 *	Time-stamp: Sun Apr 23 13:18:12 2017
 *	
 **************************************************************/

#ifndef __THEMEH__
#define __THEMEH__

#define THEMEFREQ 11025
#define THEMELEN 972288

extern const unsigned char theme[972288];

#endif /* __THEMEH__ */
